### ISSUE TITLE
[Suggestion] Possible Compatibility with MapFrontiers?

### ISSUE THREAD

**Issue by Corvus20** [YUNG-GANG/Travelers-Titles#18]
Not really sure if this is possible, but having the ability to set up named regions in [MapFrontiers](https://www.curseforge.com/minecraft/mc-mods/mapfrontiers), and having them have their names pop up as titles would be really cool.

**Comment by yungnickyoung** [comment]
According to the author of MapFrontiers, "MapFrontiers already has a GUI that shows which frontier you are on and also has the ability to announce in chat when you enter and exit a frontier."

Granted, this issue is old af so that feature might have been added after you made this. Sorry for not seeing it lol. Gonna mark it as closed since the mod author seems to have this feature already in place now, and I don't plan on supporting that mod specifically.
