### ISSUE TITLE
Objects.requireNonNull at updateDimensionTitle on login

### ISSUE THREAD

**Issue by pumkinisawesome** [YUNG-GANG/Travelers-Titles#28]
Hiya! I'm getting a wonderful error, only sometimes, when I try to join my server. With my rudimentary knowledge of Java (I'm learning at the moment), it seems to be caused by something being null that shouldn't be or something... It seems to be during updateDimensionTitle. Here is a crash log thingie that shows what happened:
https://crashy.net/otmsRNhapiG2hdQ3Bepa
Do you think this is something to do with the server, or Traveler's Titles? And what can I do to resolve this?
Thank you for any help you can give!

**Comment by yungnickyoung** [comment]
Weird, seems like the AutoRegisterSoundEvent on my API isn't always resolving properly in time. I'll take a look soon

**Comment by yungnickyoung** [comment]
Not sure the root cause yet but I attempted a hotfix to prevent crashing. Try this prelease: [https://github.com/YUNG-GANG/Travelers-Titles/releases/tag/1.19.2-Forge-3.1.2-beta0](https://github.com/YUNG-GANG/Travelers-Titles/releases/tag/1.19.2-Forge-3.1.2-beta0)

EDIT: this won't fix it either, sorry. Gonna need a bit to figure this out.

**Comment by yungnickyoung** [comment]
3.1.2 should fix this issue. Let me know if it works for you!

**Comment by pumkinisawesome** [comment]
It works wonderfully, thank you!
